apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: akshttpproxyappend
  labels:
    app: akshttpproxyappend
webhooks:
- admissionReviewVersions: ["v1"]
  name: akshttpproxyappend.default.svc.cluster.local
  clientConfig:
    caBundle: ${kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'}
    service:
      name: akshttpproxyappend
      namespace: default
      path: "/mutate"
      port: 443
  rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
  sideEffects: None